### ISSUE TITLE
'Professor' as superuser

### ISSUE THREAD

**Issue by mgree** [rwoll/submission#35]
- [x] Create capability in DB
- [x] Manage capability

**Comment by mgree** [comment]
@rwoll: where should this live?

It seems easiest just to add a boolean `professor` to the `user` record. I suppose we'd want a separate script for initializing who the professors are from the CLI, as a bootstrapping device.

Am I missing something?

(NB I'll be afk most of today and all of Sunday.)

**Comment by rwoll** [comment]
@mgree That's my initial thought to in terms of location as well (with it's default on the model being false). Once we write serializers for the different models, we can filter it out by default so we don't leak who the superusers are. 

Initializing from the command line seem's like the easiest; while it may be nice to have professorss/superusers add other professors/superusers through the web interface, I don't think it's necessary (not to mention it opens up new places for privilege escalation).

**Comment by rwoll** [comment]
#50 Adding super user and course creation.

**Comment by rwoll** [comment]
#52 Allow CLI creation and updating of professor users.
