### ISSUE TITLE
Support Git or Emailed submissions

### ISSUE THREAD

**Issue by rwoll** [rwoll/submission#38]
Allow users to submit assignments with a `git push` or to email in a submission from a registered email address.

**Comment by mgree** [comment]
I'd thought about the email one. (Git seems complicated... are they pushing to a public repo? If not, how does the submission engine get access?) I think it's best to wait for somebody to want it. :)

**Comment by rwoll** [comment]
I was thinking each person would get a unique remote address -- something like `/{semesterId}/{courseSlug}/{assignmentSlug}/{username}.git` that would use HTTPS auth. The password would be some token they could acquire through the web GUI -- similarly to how GitHub does HTTPS for people who have 2FA. Agreed that it is not something worth the technical complication until someone asks for it :)

**Comment by rwoll** [comment]
@mgree Closing this until someone asks for email submissions or git submissions 👍
