### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by mgree** [rwoll/submission#4]
Use express-session to store session info in a separate database.

**Comment by rwoll** [comment]
I'm planning on using [`connect-session-sequelize`](https://www.npmjs.com/package/connect-session-sequelize).

Some considerations:
- What should the default expiry be for the session? 
- Will implement using a database named `sage_sessions`

**Comment by mgree** [comment]
Can we make the expiry a semester long? I can imagine automatically expiring sessions with every semester change, too, but that's definitely second-order.

**Comment by rwoll** [comment]
👍 I set the default production value to 4 months, but it can easily be changed with an environment variable should we decide differently.
