### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by rwoll** [rwoll/submission#48]
Add front-end form validation (and eventually return pretty error messages from backend).

**Comment by rwoll** [comment]
@mgree How do you feel about this http://amsul.ca/pickadate.js/ for the datepicker so professors can easily select due dates and not have to type in an annoyingly formatted string?

**Comment by mgree** [comment]
The date picker looks great, but the time picker is a bit too constrained… I can imagine many people wanting to write “11:59”.

On May 31, 2016, at 10:03 PM, Ross Wollman <notifications@github.com<mailto:notifications@github.com>> wrote:


@mgree<https://github.com/mgree> How do you feel about this http://amsul.ca/pickadate.js/ for the datepicker so professors can easily select due dates and not have to type in an annoyingly formatted string?

**Comment by rwoll** [comment]
Implemented in #57. (Ideally, to validate slugs, we would poll the server for already taken slugs to make sure it is unique, but I think that is not necessary at this point.)
